export enum ErrorCode {
  // AUTHENTICATION ERRORS (1000-1999)
  INVALID_CREDENTIALS = 'AUTH_001',
  USER_NOT_FOUND = 'AUTH_002',
  ACCOUNT_LOCKED = 'AUTH_003',
  PHONE_NOT_VERIFIED = 'AUTH_004',
  ACCOUNT_SUSPENDED = 'AUTH_005',
  INVALID_TOKEN = 'AUTH_006',
  TOKEN_EXPIRED = 'AUTH_007',
  INSUFFICIENT_PERMISSIONS = 'AUTH_008',
  PASSWORD_RESET_REQUIRED = 'AUTH_009',
  TWO_FACTOR_AUTH_REQUIRED = 'AUTH_010',
  ACCOUNT_NOT_ALLOWED = 'AUTH_011',

  // VALIDATION ERRORS (2000-2999)
  INVALID_PHONE_NUMBER = 'VAL_001',
  INVALID_EMAIL = 'VAL_002',
  WEAK_PASSWORD = 'VAL_003',
  REQUIRED_FIELD_MISSING = 'VAL_004',
  INVALID_INPUT_FORMAT = 'VAL_005',
  FIELD_TOO_LONG = 'VAL_006',
  FIELD_TOO_SHORT = 'VAL_007',

  // OTP ERRORS (3000-3999)
  OTP_EXPIRED = 'OTP_001',
  OTP_INVALID = 'OTP_002',
  OTP_MAX_ATTEMPTS = 'OTP_003',
  OTP_NOT_FOUND = 'OTP_004',
  OTP_RATE_LIMIT = 'OTP_005',

  // BUSINESS LOGIC ERRORS (4000-4999)
  USER_ALREADY_EXISTS = 'BIZ_001',
  ORGANIZATION_NOT_FOUND = 'BIZ_002',
  RESOURCE_NOT_FOUND = 'BIZ_003',
  PERMISSION_DENIED = 'BIZ_004',
  QUOTA_EXCEEDED = 'BIZ_005',
  OPERATION_NOT_ALLOWED = 'BIZ_006',

  // SYSTEM ERRORS (5000-5999)
  DATABASE_ERROR = 'SYS_001',
  EXTERNAL_SERVICE_ERROR = 'SYS_002',
  SMS_SEND_FAILED = 'SYS_003',
  EMAIL_SEND_FAILED = 'SYS_004',
  CACHE_ERROR = 'SYS_005',

  // GENERIC ERRORS
  INTERNAL_SERVER_ERROR = 'GEN_001',
  BAD_REQUEST = 'GEN_002',
  UNKNOWN_ERROR = 'GEN_999',
}

export enum ErrorCategory {
  AUTHENTICATION = 'authentication',
  VALIDATION = 'validation',
  BUSINESS = 'business',
  SYSTEM = 'system',
  PERMISSION = 'permission',
}

export enum ErrorSeverity {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}
